app:
  port: "8088"
  mode: development
  base_url: http://localhost:8088

db:
  host: localhost
  port: "5999"
  user: ray
  password: ray
  name: ray
  ssl_mode: disable
  time_zone: Asia/Ulaanbaatar
